In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [86]:
a=np.arange(10)
print(a)
print(type(a))


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [11]:
l=range(100)
%timeit [i**2 for i in l]


12 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [90]:
a=np.arange(10)
%timeit a**2
print(type(a))
print(a.dtype)

937 ns ± 7.51 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
<class 'numpy.ndarray'>
int32


# #creating arrays1

In [18]:
a=np.array([1,2,3,4,])

In [20]:
print(a.ndim)

1


In [38]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [26]:
print(b.ndim)

2


In [40]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
print(c.ndim)

3


In [44]:
print(a.shape)

(4,)


In [46]:
print(b.shape)

(2, 3)


In [48]:
print(c.shape)

(2, 2, 2)


#  functions for creating array

In [52]:
a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [60]:
a=np.arange(0,10,2)
print(a)


[0 2 4 6 8]


In [63]:
#using linespace
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [65]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [67]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [73]:
a=np.eye(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
a=np.eye(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [79]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [81]:
a=np.diag([1,2,3,4])
print(a)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [83]:
print(np.diag(a))

[1 2 3 4]


# basic datatype

In [92]:
a=np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [98]:
a=np.arange(10,dtype=float)
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [100]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# other datatype

In [103]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [105]:
a=np.array([True,False])
print(a.dtype)

bool


In [109]:
a=np.array(['vinay','venu','aditya degree college'])
print(a.dtype)

<U21


# indexing and slicing

In [117]:
a=np.arange(10)
print(a)
print(a[5])

[0 1 2 3 4 5 6 7 8 9]
5


# Slicing

In [120]:
a=np.arange(10)

In [ ]:
print

# copies and viewing

In [128]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [130]:
print(np.shares_memory(a,b))

True


In [132]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [134]:
print(np.shares_memory(a,b))

False


# random number generator

In [139]:
a=np.random.randint(0,20,15)
print(a)

[18 14 19  7  2  4 12  9  4  7 12 19  6 13 12]


In [141]:
mask=(a%2==0)

In [156]:
a[mask]= "*"
print(a)

ValueError: invalid literal for int() with base 10: '*'